model: "vqvae"

downsample_factor: 2
codebook_dim: 64
num_embeddings: 128

do_wandb: true  # Whether to use Wandb for logging
use_amp: True  # Enable bf16 mixed precision (torch.autocast) to cut activation memory and allow a bigger batch size

dataset_name: "imagenette" # Options: pineapple, cifar10, mnist, imagenette
resize_img: 256
batch_size: 8                # Batch size for training
lr: 0.0001                     # Learning rate
do_early_stopping: False
epochs: 100                   # Number of training epochs
patience: 15                # Early stopping patience
checkpoints: "./checkpoints/vqvae/"  # Checkpoint save path
train_ratio: 0.8            # Train ratio
val_ratio: 0.2
device: "cuda"              # Device
architecture: "cuda"        # Model architecture
dataset_path: "./datasets/imagenette2-320"  # Dataset path
wandb_project: "dual_vae"  # Wandb Project Name
wandb_entity: "imagine-laboratory-conare"  # Wandb Project Entity
seed: 42

commitment_cost: 0.25
deterministic: True
cudnn_benchmark: False
num_workers: 4